#!/bin/sh

# Remove the ipkg wrapper
/usr/bin/ipkg -o /var remove org.webosinternals.fairdinkum
rm -f /usr/local/bin/ipkg

# Remove obsolete feeds
rm -f /var/usr/lib/ipkg/lists/autopatch* /var/etc/ipkg/autopatch.conf*
rm -f /var/usr/lib/ipkg/lists/preyourmind* /var/etc/ipkg/preyourmind.conf*

if [ -z "$IPKG_OFFLINE_ROOT" ]; then
  IPKG_OFFLINE_ROOT=/var
fi

# Is the app limit fixed?
if [ -d /media/cryptofs/apps ] ; then
  APPS=/media/cryptofs/apps
else
  APPS=/var
  # Install the ipkg wrapper
  mkdir -p /usr/local/bin
  cp /var/usr/palm/applications/org.webosinternals.ipkgservice/files/ipkg /usr/local/bin/ipkg
fi

# Install the java dbus service
rm -f /usr/lib/luna/java/org.webosinternals.ipkgservice.jar
cp $IPKG_OFFLINE_ROOT/usr/lib/luna/java/org.webosinternals.ipkgservice.jar /usr/lib/luna/java/org.webosinternals.ipkgservice.jar
rm -f /usr/share/dbus-1/system-services/org.webosinternals.ipkgservice.service
cp $IPKG_OFFLINE_ROOT/usr/share/dbus-1/system-services/org.webosinternals.ipkgservice.service /usr/share/dbus-1/system-services/org.webosinternals.ipkgservice.service

# Install the upstart script
rm -f /etc/event.d/org.webosinternals.ipkgservice
cp $IPKG_OFFLINE_ROOT/etc/event.d/org.webosinternals.ipkgservice /etc/event.d/org.webosinternals.ipkgservice

# Transition the feed configuration files
if [ "$IPKG_OFFLINE_ROOT" == "/var" -a "$APPS" == "/media/cryptofs/apps" ] ; then
    cp $IPKG_OFFLINE_ROOT/etc/ipkg/* $APPS/etc/ipkg/
fi

# Set up the architecture configuration file
rm -f $APPS/etc/ipkg/arch.conf
cp /etc/ipkg/arch.conf $APPS/etc/ipkg/arch.conf

# Install webosinternals feeds
echo "src/gz webosinternals http://ipkg.preware.org/feeds/webos-internals/all" > $APPS/etc/ipkg/webos-internals.conf
echo "src/gz webosinternals-`/bin/uname -m` http://ipkg.preware.org/feeds/webos-internals/`/bin/uname -m`" >> $APPS/etc/ipkg/webos-internals.conf
sed -i -e 's|armv7l|armv7|g' $APPS/etc/ipkg/webos-internals.conf
sed -i -e 's|armv6l|armv6|g' $APPS/etc/ipkg/webos-internals.conf

# Install optware feeds
echo "src/gz optware http://ipkg.preware.org/feeds/optware/all" > $APPS/etc/ipkg/optware.conf
echo "src/gz optware-`/bin/uname -m` http://ipkg.preware.org/feeds/optware/`/bin/uname -m`" >> $APPS/etc/ipkg/optware.conf
sed -i -e 's|armv7l|armv7|g' $APPS/etc/ipkg/optware.conf
sed -i -e 's|armv6l|armv6|g' $APPS/etc/ipkg/optware.conf

# Configure the webos-patches feed
VERSION=`grep PRODUCT_VERSION_STRING /etc/palm-build-info | sed -e 's/.*=Palm webOS \([0-9.]*\).*/\1/'`
sed -i -e "s^/\(all\|[0-9.]*\)\$^/$VERSION^g" $APPS/etc/ipkg/webos-patches.conf

# Retain disabled status of feeds
if [ "`ls $APPS/etc/ipkg/*.disabled`" ] ; then
  for f in $APPS/etc/ipkg/*.disabled ; do
    if [ -f $APPS/etc/ipkg/`basename $f .disabled` ] ; then
      rm -f $f
      mv $APPS/etc/ipkg/`basename $f .disabled` $f
    fi
  done
fi

exit 0
