#!/bin/sh

# Install the java dbus service
rm -f /usr/lib/luna/java/org.webosinternals.ipkgservice.jar
ln -s /var/usr/lib/luna/java/org.webosinternals.ipkgservice.jar /usr/lib/luna/java/org.webosinternals.ipkgservice.jar
rm -f /usr/share/dbus-1/system-services/org.webosinternals.ipkgservice.service
ln -s /var/usr/share/dbus-1/system-services/org.webosinternals.ipkgservice.service /usr/share/dbus-1/system-services/org.webosinternals.ipkgservice.service

# Install the upstart script
rm -f /etc/event.d/org.webosinternals.ipkgservice
cp /var/etc/event.d/org.webosinternals.ipkgservice /etc/event.d/org.webosinternals.ipkgservice

# Set up the architecture configuration file
rm -f /var/etc/ipkg/arch.conf
ln -s /etc/ipkg/arch.conf /var/etc/ipkg/arch.conf

# Install the ipkg wrapper
/usr/bin/ipkg -o /var remove org.webosinternals.fairdinkum
rm -f /usr/local/bin/ipkg
mkdir -p /usr/local/bin
ln -s /var/usr/palm/applications/org.webosinternals.ipkgservice/files/ipkg /usr/local/bin/ipkg

# Install webosinternals feeds
echo "src/gz webosinternals http://ipkg.preware.org/feeds/webos-internals/all" > /var/etc/ipkg/webos-internals.conf
echo "src/gz webosinternals-`/bin/uname -m` http://ipkg.preware.org/feeds/webos-internals/`/bin/uname -m`" >> /var/etc/ipkg/webos-internals.conf
sed -i -e 's|armv7l|armv7|g' /var/etc/ipkg/webos-internals.conf

# Install optware feeds
echo "src/gz optware http://ipkg.preware.org/feeds/optware/all" > /var/etc/ipkg/optware.conf
echo "src/gz optware-`/bin/uname -m` http://ipkg.preware.org/feeds/optware/`/bin/uname -m`" >> /var/etc/ipkg/optware.conf
sed -i -e 's|armv7l|armv7|g' /var/etc/ipkg/optware.conf

# Install preyourmind feeds
echo "src/gz preyourmind http://preyourmind.org/services/feed/arch_all" > /var/etc/ipkg/preyourmind.conf
echo "src/gz preyourmind-`/bin/uname -m` http://preyourmind.org/services/feed/arch_`/bin/uname -m`" >> /var/etc/ipkg/preyourmind.conf
sed -i -e 's|armv7l|armv7|g' /var/etc/ipkg/preyourmind.conf

# Remove obsolete lists
rm -f /var/usr/lib/ipkg/lists/all /var/usr/lib/ipkg/lists/armv7 /var/usr/lib/ipkg/lists/i686

# Remove obsolete feeds
rm -f /var/usr/lib/ipkg/lists/autopatch /var/etc/ipkg/autopatch.conf

# Retain disabled status of feeds
if [ "`ls /var/etc/ipkg/*.disabled`" ] ; then
  for f in /var/etc/ipkg/*.disabled ; do
    if [ -f /var/etc/ipkg/`basename $f .disabled` ] ; then
      rm -f $f
      mv /var/etc/ipkg/`basename $f .disabled` $f
    fi
  done
fi

# Restart the service handler (this also starts this service)
if [ -z "$IPKG_OFFLINE_ROOT" ]; then # Defined by recent installers that also support flags.
    /sbin/stop java-serviceboot
    /sbin/start java-serviceboot
fi

exit 0
