#!/bin/sh

# Handle execution as pmPreRemove.script
if [ -z "$IPKG_OFFLINE_ROOT" ]; then
  IPKG_OFFLINE_ROOT=/media/cryptofs/apps
  mount -o remount,rw /
fi

APPS=/media/cryptofs/apps

# Remove all list database cache files
rm -f $APPS/usr/lib/ipkg/lists/*
rm -f $APPS/usr/lib/ipkg/cache/*

# Stop the service
/sbin/stop org.webosinternals.ipkgservice

# Remove the java dbus service
rm -f /usr/lib/luna/java/org.webosinternals.ipkgservice.jar
rm -f /usr/share/dbus-1/system-services/org.webosinternals.ipkgservice.service

# Remove the upstart script
rm -f /etc/event.d/org.webosinternals.ipkgservice

exit 0
