#!/bin/sh

# Remove the ipkg wrapper
rm -f /usr/local/bin/ipkg

# Stop the service
/sbin/stop org.webosinternals.ipkgservice

# Remove the java dbus service
rm -f /usr/lib/luna/java/org.webosinternals.ipkgservice.jar
rm -f /usr/share/dbus-1/system-services/org.webosinternals.ipkgservice.service

# Remove the upstart script
rm -f /etc/event.d/org.webosinternals.ipkgservice

exit 0
